name: Pull request QA

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js v14.21.1
        uses: actions/setup-node@v3
        with:
          node-version: 14.21.1
          cache: 'npm'

      - name: Install Npm 6.14.17
        run: npm install -g npm@6.14.17

      - name: Install dependencies
        run: npm install

      - name: Build Frontend
        run: npm run build --prod
